version: '2.4'
services:
  trusty:
    build: ../../dockerfiles/trusty
    command: bash -c "cd src && tox -e trusty && dpkg-buildpackage -d -uc -us && mv ../*.deb ../dist/"
    volumes:
     - ../..:/work
