version: '2.4'
services:
  trusty:
    build: ../../dockerfiles/trusty
    command: bash -c "cp -R /code/* /work && cd /work/src && tox -e trusty && dpkg-buildpackage -d -uc -us && mv ../*.deb /dist"
    volumes:
      - ../..:/code:ro
      - ../../dist:/dist
