[tox]
envlist=py312-linux
skipsdist = true
requires =
    pip==25.2
    setuptools==80.10.1
    wheel==0.46.2
    virtualenv==20.24.6

[testenv]
basepython = python3.12
passenv = DOCKER_TLS_VERIFY,DOCKER_HOST,DOCKER_CERT_PATH
setenv =
    TZ = UTC
    PIP_INDEX_URL = {env:PIP_INDEX_URL:https://pypi.yelpcorp.com/simple}

[testenv:.tox]
basepython = python3.12

[testenv:py312-linux]
deps =
    -r{toxinidir}/requirements.txt

[testenv:tests]
envdir = .tox/py312-linux/
recreate = false
deps =
    {[testenv:py312-linux]deps}
    -r{toxinidir}/requirements-dev.txt
    --editable={toxinidir}
commands =
    coverage run -m pytest {posargs:tests}
    coverage report -m --include nerve_tools/* --show-missing --skip-covered --fail-under 75
    flake8 nerve_tools tests

[flake8]
max-line-length = 120

[testenv:mypy]
envdir = .tox/py312-linux/
recreate = false
deps =
    {[testenv:tests]deps}
setenv =
    {[testenv]setenv}
    MYPYPATH = {toxinidir}
mypy_paths =
    nerve_tools
commands =
    mypy --no-warn-unused-ignores {posargs:{[testenv:mypy]mypy_paths}}

[testenv:package_jammy]
allowlist_externals =
    cp
    docker
setenv =
    {[testenv]setenv}
    COMPOSE_FILE = dockerfiles/jammy/docker-compose.yml
    SSH_AUTH_SOCK={env:SSH_AUTH_SOCK}
commands =
    cp dockerfiles/itest/itest/yelpsoa-configs/location_mapping.json dockerfiles/itest/itest/yelpsoa-configs/location_types.json dockerfiles/jammy/
    docker compose down
    docker compose build --no-cache --build-arg PIP_INDEX_URL={env:PIP_INDEX_URL:https://pypi.yelpcorp.com/simple}
    docker compose run jammy
    docker compose stop
    docker compose rm --force

[testenv:itest_jammy]
allowlist_externals = docker
setenv =
    {[testenv]setenv}
    COMPOSE_PROJECT_NAME=nerve_tools_jammy
    COMPOSE_FILE = dockerfiles/itest/docker-compose-jammy.yml
    SSH_AUTH_SOCK={env:SSH_AUTH_SOCK:}
commands =
    docker compose down
    docker compose build --no-cache --build-arg PIP_INDEX_URL={env:PIP_INDEX_URL:https://pypi.yelpcorp.com/simple}
    docker compose run itest
    docker compose stop
    docker compose rm --force
