[tox]
envlist = py
indexserver =
    default = http://pypi.yelpcorp.com/simple/

[testenv]
# wheels for Lucid will not work on Trusty
install_command = pip install --no-use-wheel --upgrade {opts} {packages}
deps = -r/work/src/requirements.txt

[testenv:py]
deps =
    {[testenv]deps}
    flake8
    pytest
    mock
commands =
    py.test {posargs:tests}
    flake8 nerve_tools tests

[flake8]
ignore = E501
