[tox]
indexserver =
    default = http://pypi.yelpcorp.com/simple/

[testenv]
# wheels for Lucid will not work on Trusty
install_command = pip install --no-use-wheel --upgrade {opts} {packages}
basepython=python2.7
deps =
     -r/work/src/requirements.txt
    flake8
    pytest
    mock
commands =
    py.test {posargs:tests}
    flake8 nerve_tools tests

[testenv:lucid]

[testenv:trusty]

[flake8]
ignore = E501
